name = "product-discount"
type = "product_discounts"
api_version = "2022-07"

[build]
command = ""
path = "dist/function.wasm"

[ui.paths]
create = "/ui/product-discount/new"
details = "/ui/product-discount/:id"
